steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Preparegustus-image-apiArchive'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        touch gustus-image-api.tar.gz
        tar --exclude=gustus-image-api.tar.gz --exclude='.git' --exclude='node_modules' -zcvf gustus-image-api.tar.gz .

  # Step 2: Copy the archive to the Compute Engine instance
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'CopyArchive'
    args:
      - compute
      - scp
      - gustus-image-api.tar.gz
      - '$_GCE_USERNAME@$_GCE_INSTANCE:~/'
      - --zone=$_GCE_ZONE
      - --project=$_PROJECT_ID

  # Step 3: SSH into the instance, unpack the archive, and set up the environment
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'SetupAndDeploy'
    args:
      - compute
      - ssh
      - '$_GCE_USERNAME@$_GCE_INSTANCE'
      - '--zone=$_GCE_ZONE'
      - '--command'
      - |
        mkdir -p ~/gustus-image-api && \
        tar -zxvf ~/gustus-image-api.tar.gz -C ~/gustus-image-api && \
        cd ~/gustus-image-api && \
        sudo docker build -t gustus-image-api:latest . && \
        sudo docker stop gustus-image-api-container || true && \
        sudo docker run --rm -d --name gustus-image-api-container \
          -p 3030:3003 \
          -e NODE_ENV=$_NODE_ENV \
          -e MONGO_URI=$_MONGO_URI \
          -e JWT_KEY=$_JWT_KEY \
          gustus-image-api:latest

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'

