steps:
  - id: 'Deploying'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'functions'
      - 'deploy'
      - '$_PROJECT_NAME'
      - '--gen2'
      - '--source=.'
      - '--trigger-http'
      - '--min-instances=0'
      - '--max-instances=1'
      - '--runtime=nodejs20'
      - '--region=$_REGION'
      - '--entry-point=service'
      - '--allow-unauthenticated'
      - '--project=$_GCLOUD_PROJECT'
      - '--vpc-connector=$_VPC_CONNECTOR'
      - '--set-secrets=NODE_ENV=GUSTUS_NODE_ENV:latest'
      - '--set-secrets=MONGO_URI=GUSTUS_MONGO_URI:latest'
      - '--set-secrets=JWT_KEY=GUSTUS_JWT_KEY:latest'
      - '--service-account=$_SERVICE_ACCOUNT'

options:
  logging: CLOUD_LOGGING_ONLY

tags:
  - master
  - beta

