name: Sync Folders to Branches

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'Hexcss'
          git config --global user.email 'cadersuay.javier@gmail.com'

      - name: Push changes to corresponding branches
        env:
          REPO: Hexcss/uni-bdd-2-project.git
          ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          FOLDERS="api-crud api-auth api-images front-cms front-landing"
          for folder in $FOLDERS; do
            # Always sync changes
            echo "Syncing $folder"
            # Check if the branch exists, create if not
            if ! git ls-remote --heads https://x-access-token:${ACCESS_TOKEN}@github.com/${REPO} $folder; then
              echo "Branch $folder does not exist, creating from master"
              git subtree split --prefix=$folder -b $folder-branch
              git push https://x-access-token:${ACCESS_TOKEN}@github.com/${REPO} $folder-branch:$folder
              git branch -D $folder-branch
            fi

            # Create a temporary branch to push changes
            git subtree split --prefix=$folder -b temp-branch
            # Ensure branch is up to date or create if it doesn't exist
            git fetch origin $folder:$folder || git branch $folder origin/master
            git checkout $folder
            git reset --hard temp-branch
            git push https://x-access-token:${ACCESS_TOKEN}@github.com/${REPO} $folder -f
            git checkout master
            git branch -D temp-branch

          done
