name: Sync Folders to Branches

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Set up Git
        run: |
          git config --global user.name 'Hexcss'
          git config --global user.email 'cadersuay.javier@gmail.com'

      - name: Push changes to corresponding branches
        env:
          REPO: Hexcss/uni-bdd-2-project.git
          ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          FOLDERS="api-crud api-auth api-images front-cms front-landing"
          for folder in $FOLDERS; do
            echo "Checking for changes in $folder"

            # Ensure all branches are available locally
            git fetch --all

            # Check if the branch exists
            if git show-ref --verify --quiet refs/heads/$folder; then
              # Branch exists, compare it with the master branch
              if ! git diff --quiet origin/master:$folder $folder; then
                echo "$folder has changes. Syncing..."
                # Logic to sync changes
                git subtree split --prefix=$folder -b temp-branch
                git checkout $folder
                git merge temp-branch -m "Syncing $folder with master"
                git push https://x-access-token:${ACCESS_TOKEN}@github.com/${REPO} $folder
                git checkout master
                git branch -D temp-branch
              else
                echo "No changes in $folder. No sync needed."
              fi
            else
              # Branch does not exist, create and push
              echo "Branch $folder does not exist, creating from master"
              git subtree split --prefix=$folder -b $folder
              git push https://x-access-token:${ACCESS_TOKEN}@github.com/${REPO} $folder:$folder
              git branch -D $folder
            fi
          done
